// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA93elnDi3lK6Xq36bkVHzIqhtkWyUS0c',
    appId: '1:514380820902:web:941f39e28f8be33e8e9f67',
    messagingSenderId: '514380820902',
    projectId: 'instadate-now',
    authDomain: 'instadate-now.firebaseapp.com',
    storageBucket: 'instadate-now.firebasestorage.app',
    measurementId: 'G-QTBYY16RC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmPY9w4wjtNkMdmVr6hpwbmvdpFJPN4k',
    appId: '1:514380820902:android:3865590dc23bf50c8e9f67',
    messagingSenderId: '514380820902',
    projectId: 'instadate-now',
    storageBucket: 'instadate-now.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifLaJLQ-oUKl_eRobT9DK7X61xjkZxAA',
    appId: '1:514380820902:ios:78c8e345a0c2f30e8e9f67',
    messagingSenderId: '514380820902',
    projectId: 'instadate-now',
    storageBucket: 'instadate-now.firebasestorage.app',
    iosBundleId: 'com.example.instadate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifLaJLQ-oUKl_eRobT9DK7X61xjkZxAA',
    appId: '1:514380820902:ios:78c8e345a0c2f30e8e9f67',
    messagingSenderId: '514380820902',
    projectId: 'instadate-now',
    storageBucket: 'instadate-now.firebasestorage.app',
    iosBundleId: 'com.example.instadate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA93elnDi3lK6Xq36bkVHzIqhtkWyUS0c',
    appId: '1:514380820902:web:56a3d444bbaee3fe8e9f67',
    messagingSenderId: '514380820902',
    projectId: 'instadate-now',
    authDomain: 'instadate-now.firebaseapp.com',
    storageBucket: 'instadate-now.firebasestorage.app',
    measurementId: 'G-F0KPRJ3EBF',
  );
}
